export const ABOUT_URL = process.env.ABOUT_URL;
export const EDUCATION_URL = process.env.EDUCATION_URL;
export const EXPERIENCE_URL = process.env.EXPERIENCE_URL;
export const SKILLS_URL = process.env.SKILLS_URL;
export const SITE_URL = process.env.SITE_URL;
export const CONTACT_URL = process.env.CONTACT_URL;
export const SECRET_KEY = process.env.SECRET_KEY;
export const USER_NAME = process.env.USER_NAME || "admin";
export const PASS_WORD = process.env.PASS_WORD || "admin";
