name: CICD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Docker Image
        run: docker build -t  dashsomsekhar/pwsite . 
      - name: Publish the image into docker hub
        run: docker push dashsomsekhar/pwsite:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull the image from docker hub
        run: docker pull dashsomsekhar/pwsite:latest
      - name: Delete the old container
        run: docker rm -f theContainer
      - name: Run the docker container
        run: docker run --init -p 5000:5000 -d --name theContainer dashsomsekhar/pwsite:latest



      



      
